Resolve byte error
Traceback (most recent call last):
  File "/scripts/xDP-Walker/cisco.py", line 496, in <module>
    main()
  File "/scripts/xDP-Walker/cisco.py", line 430, in main
    current.writerow(["name", "ip", "remote", "model", "description", "error"])
TypeError: a bytes-like object is required, not 'str'